name = "AutoForward"
uuid = "45e47a89-b455-4dd5-a62c-c007f63154db"
authors = ["cschen <camillo.schenone@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia="1.10"
Combinatoris = "1"
InteractiveUtils = "1"
